#!/usr/bin/perl
use strict;
use warnings;

# http://www.huygens-fokker.org/docs/scales.zip

use Data::Dumper::Compact qw(ddc);
use Music::Scala ();
use Music::Intervals::Numeric;

my $file = shift || "$ENV{HOME}/Music/scl/werck1.scl"; # ellis_r.scl

my $m = Music::Intervals::Numeric->new;

my $scala = Music::Scala->new(file => $file);

print $scala->get_description, "\n";

for my $interval ($scala->get_notes) {
    my $name = $m->ratios->{$interval} || '?';
    print "\t$interval: $name\n";
}
