#!/usr/bin/perl
use strict;
use warnings;

# http://www.huygens-fokker.org/docs/scales.zip

use Data::Dumper::Compact qw(ddc);
use Music::Scala ();
use Music::Intervals::Numeric;

my $file = shift || "$ENV{HOME}/Music/scl/werck1.scl";

my $m = Music::Intervals::Numeric->new;

my $scala = Music::Scala->new(file => $file);

print $scala->get_description, "\n";

my $i = 0;

for my $interval ($scala->get_notes) {
    $i++;
    my $approx = eval $interval;
    my $name = $m->ratios->{$interval} || '?';
    printf "\t%d. %s (%.4f) %s\n", $i, $interval, $approx, $name;
}
